<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


In [2]:
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""


def factorial(n):
    import numpy as np
    if n == 0:
        return 1
    elif n < 0:
        return "cannot be a negative number"
    else:
        fa = np.arange(1, n+1)
        return np.prod(fa)

In [6]:
factorial(5)

120

In [15]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    import numpy as np
    if n == 0:
        return 1
    elif n < 0:
        return "cannot be a negative number"
    else:
        fa = np.arange(1,n+1)
        return np.cumprod(fa)

In [16]:
all_factorials(5)

array([  1,   2,   6,  24, 120])

<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [7]:
def get_pct_changes(file_name):
    import numpy as np
    data = np.genfromtxt(file_name,delimiter=",")
    data_c = data[np.logical_not(np.isnan(data))]
    change = np.diff(data_c)/data_c[:-1]
    return change
    

In [9]:
get_pct_changes('apple.csv')

array([-0.05217305, -0.07339571,  0.02475207, ..., -0.00977899,
       -0.00882215,  0.01720356])

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, one-day percent change to the file 
<li>Groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each of the groups



In [22]:
datafile = "apple.csv"
import pandas as pd
import numpy as np

df = pd.read_csv('apple.csv',na_values='null')
df['One-day Percent Change'] = df["Adj Close"].pct_change()

def GroupbyCat (df, ind, col):
    if df[col].loc[ind] > 0.025:
        return 'High+'
    elif df[col].loc[ind] >= 0:
        return 'Low+'
    elif df[col].loc[ind] >= -0.025:
        return 'Low-'
    elif df[col].loc[ind] < -0.025:
        return 'High-'
    else:
        return None

groupchg = df.groupby(lambda x: GroupbyCat(df,x, 'One-day Percent Change'))
groupchg.size()


High+    1391
High-    1210
Low+     3535
Low-     3140
dtype: int64

In [25]:
groupchg.mean()

Adj Close  One-day Percent Change
High+   8.331002                0.045705
High-   8.740214               -0.044232
Low+   23.528533                0.009882
Low-   24.385841               -0.011171